
```{r fig.height=4.5, fig.width=6}
library(Seurat)
library(dplyr)
library(patchwork)
library(Matrix)
library(cowplot)
library(ggplot2)
library(harmony)
library(RColorBrewer)
library(ggrepel)
library(tidyverse)
library(reshape2)
library(future)
# Load the sample dataset
```




```{r}
######## Process Depleted and Control datasets
data.Control1 <- Read10X(data.dir = "C:/Users/bg/Documents/data/INJ1")
data.Control2 <- Read10X(data.dir = "C:/Users/bg/Documents/data/INJ2")
data.Depleted1 <- Read10X(data.dir = "C:/Users/bg/Documents/data/ABINJ1")
data.Depleted2 <- Read10X(data.dir = "C:/Users/bg/Documents/data/ABINJ2")

data.Control1 <- CreateSeuratObject(data.Control1, assay = "RNA",
                                   min.cells = 3, # Include genes with detected expression in at least this many cells (3 cells)
                                   min.features = 200, # Include cells where at least this many genes are detected (200 genes)
                                   project = 'Control1')
data.Control2 <- CreateSeuratObject(data.Control2, assay = "RNA",
                                   min.cells = 3, # Include genes with detected expression in at least this many cells (3 cells)
                                   min.features = 200, # Include cells where at least this many genes are detected (200 genes)
                                   project = 'Control2')

data.Control <- merge (data.Control1,data.Control2)

data.Control <- RenameCells(data.Control, add.cell.id = "Control")
data.Control@meta.data$sample <- "Control"
data.Control[["percent.mt"]] <- PercentageFeatureSet(data.Control, pattern = "^mt-")
data.Control[["percent.ribo"]] <- PercentageFeatureSet(data.Control, pattern = "^rp")
VlnPlot(data.Control, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0.01)
data.Control_clean <- subset(data.Control, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 20)

data.Depleted1 <- CreateSeuratObject(data.Depleted1, assay = "RNA",
                                   min.cells = 3, # Include genes with detected expression in at least this many cells (3 cells)
                                   min.features = 200, # Include cells where at least this many genes are detected (200 genes)
                                   project = 'Depleted1')
data.Depleted2 <- CreateSeuratObject(data.Depleted2, assay = "RNA",
                                   min.cells = 3, # Include genes with detected expression in at least this many cells (3 cells)
                                   min.features = 200, # Include cells where at least this many genes are detected (200 genes)
                                   project = 'Depleted2')

data.Depleted <- merge(data.Depleted1,data.Depleted2)
data.Depleted <- RenameCells(data.Depleted, add.cell.id = "Depleted")
data.Depleted@meta.data$sample <- "Depleted"
data.Depleted[["percent.mt"]] <- PercentageFeatureSet(data.Depleted, pattern = "^mt-")
data.Depleted[["percent.ribo"]] <- PercentageFeatureSet(data.Depleted, pattern = "^rp")
VlnPlot(data.Depleted, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0.01)
data.Depleted_clean <- subset(data.Depleted, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 20)

# I will explain you what this step is doing after talking with Mike
data.Depleted_clean_subsampled <- data.Depleted_clean[, sample(colnames(data.Depleted_clean), size = 6263, replace=F)]

data.integrated_inj <- merge(data.Control_clean,data.Depleted_clean_subsampled)

data.integrated_inj[["RNA"]] <- JoinLayers(data.integrated_inj[["RNA"]])
```

```{r}
data.integrated_inj <- NormalizeData(data.integrated_inj, verbose = T)
data.integrated_inj <- FindVariableFeatures(data.integrated_inj, selection.method = "vst", nfeatures = 2500, verbose = T)
data.integrated_inj <- ScaleData(data.integrated_inj, features=rownames(data.integrated_inj),verbose = T)
data.integrated_inj <- RunPCA(data.integrated_inj, pc.genes = data.integrated_inj@var.genes, npcs = 30, verbose = T)
ElbowPlot(data.integrated_inj, ndims = 30)
```

```{r}

data.integrated_inj <- FindNeighbors(data.integrated_inj, dims = 1:15)
data.integrated_inj <- FindClusters(data.integrated_inj, resolution = 1.0)
data.integrated_inj <- RunUMAP(data.integrated_inj, dims = 1:15,metric = 'euclidean')
```


```{r fig.height=4, fig.width=5}
## Plotting and having a look at the data
color.vector <- c( brewer.pal(12, "Set3"),brewer.pal(8, "Set1"), brewer.pal(8, "Dark2"), brewer.pal(8, "Accent"),brewer.pal(8, "Pastel1"))
DimPlot(data.integrated_inj, reduction = "umap", pt.size = 0.1, label = T, cols = color.vector,repel=T)
DimPlot(data.integrated_inj, reduction = "umap", pt.size = 0.1, label = F, group.by="orig.ident", cols = color.vector)

DimPlot(data.integrated_inj, reduction = "umap", pt.size = 0.1, label = F, group.by="sample", cols = c("blue","red"),shuffle=T)



table(data.integrated_inj@meta.data$seurat_clusters, data.integrated_inj@meta.data$sample)
```




```{r}
current.cluster.ids <- c(0, 1, 2, 3, 4, 5, 6, 7,8,9,10,11,12,13,14,15,16,17,18,19,20)
new.cluster.ids <- c("Monocytes/Macrophages", 
                     "Monocytes/Macrophages", 
                     "Monocytes/Macrophages", 
                     "Monocytes/Macrophages",
                     "Monocytes/Macrophages", 
                     "Monocytes/Macrophages",
                  "Monocytes/Macrophages",
                   "Monocytes/Macrophages",
                   "FAPs",
                   "Monocytes/Macrophages",
                     "Monocytes/Macrophages", 
                  "Monocytes/Macrophages",
                     "Antigen-presenting Cells", 
                     "Monocytes/Macrophages", 
                      "Endothelial Cells", 
                  "Satellite Cells",
                 "Monocytes/Macrophages", 
                 "Neutrophils",
                 "Tenocytes",
                 "Antigen-presenting Cells",
                 "NK/T Cells"
                   )
data.integrated_inj@meta.data$cellid <- data.integrated_inj@meta.data$seurat_clusters

data.integrated_inj@meta.data[["cellid"]] <- plyr::mapvalues(x = data.integrated_inj@meta.data[["cellid"]], from = current.cluster.ids, to = new.cluster.ids)


```

```{r fig.height=4, fig.width=8.5}
#Fig.4A

color.vector <- c("#E41A1C","#377EB8","#1EDC87","#984EA3","#FF7F00","#A65628","#F781BF","#d78a7d")


DimPlot(data.integrated_inj, reduction = "umap", pt.size = 0.15, label = F, cols = color.vector,group.by="cellid",split.by="sample",repel=T)


table(data.integrated_inj@meta.data$cellid, data.integrated_inj@meta.data$sample)
```


```{r fig.height=4, fig.width=10}
DotPlot(data.integrated_inj,group.by="cellid",features=c("Cd68","Pdgfra","H2-Aa","H2-Ab1","Pecam1","Cdh5","Pax7","Myod1","Ly6g","Retnlg","S100a8","Fmod","Tnmd","Scx","Nkg7","Cd3d"),  cols = c("lightgrey", "#35553B"))+ RotatedAxis() + ylab(NULL)+xlab('Gene') +  theme(

                    axis.title.x = element_text(size = 16),
                    axis.text.y = element_text(size = 16),
                    axis.text.x = element_text(size = 16))
```


```{r}
#Setting identity to each cluster
#Myeloid cells don't include neutrophils. The neutrophils are in a single cluster.

current.cluster.ids <- c("Endothelial Cells",
"Satellite Cells",
"Tenocytes",
"Neutrophils",
"FAPs",
"Monocytes/Macrophages",
"Antigen-presenting Cells",
"NK/T Cells")

new.cluster.ids <- c("EC",
"SC",
"Teno",
"Neut",
"FAP",
"Mo/Mφ",
"APC",
"NK/T"
)
data.integrated_inj@meta.data$shortid <- data.integrated_inj@meta.data$cellid
data.integrated_inj@meta.data[["shortid"]] <- plyr::mapvalues(x = data.integrated_inj@meta.data[["shortid"]], from = current.cluster.ids, to = new.cluster.ids)
```


```{r fig.height=8, fig.width=10}
#Fig.S2F
DefaultAssay(data.integrated_inj) <- "RNA"
Idents(data.integrated_inj) <- "cellid"
inj_markers_all_RNA <- FindAllMarkers(object = data.integrated_inj, only.pos = T, min.pct = 0.25, logfc.threshold = 0.25) 

pval <- inj_markers_all_RNA[,c(1)]
adj_p <- p.adjust(pval, method = "BH", n = length(pval))

inj_markers_all_RNA$adj_pval <- adj_p

inj_markers_all_RNA_subset <- inj_markers_all_RNA %>% filter(adj_pval <= 0.05)


top10 <- inj_markers_all_RNA_subset %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)




DoHeatmap(data.integrated_inj, features = top10$gene,group.color=c("#E41A1C","#377EB8","#1EDC87","#984EA3","#FF7F00","#A65628","#F781BF","#d78a7d")) + scale_fill_gradientn(colors = c("blue", "white", "red"))
```

