```{r}
library(CellChat)
library(patchwork)
options(stringsAsFactors = FALSE)
```

```{r}
#Note: You can either use data.integrated_inj or data.integrated_homeo for the input
#Take regeneration for example
precellchat.int.new.control <- subset(x = data.integrated_homeo, subset = sample == "Control")
cellchat.int.new.control <- createCellChat(object = precellchat.int.new.control, group.by = "cellid", assay = "RNA")
```





```{r}
CellChatDB <- CellChatDB.mouse 
showDatabaseCategory(CellChatDB)
# Show the structure of the database
dplyr::glimpse(CellChatDB$interaction)
CellChatDB.use <- CellChatDB
# set the used database in the object
cellchat.int.new.control@DB <- CellChatDB.use
```

```{r}
# subset the expression data of signaling genes for saving computation cost
cellchat.int.new.control <- subsetData(cellchat.int.new.control) # This step is necessary even if using the whole database
#future::plan("multisession", workers = 8) # do parallel
cellchat.int.new.control <- identifyOverExpressedGenes(cellchat.int.new.control)
cellchat.int.new.control <- identifyOverExpressedInteractions(cellchat.int.new.control)
```

```{r}
cellchat.int.new.control <- computeCommunProb(cellchat.int.new.control)
# Filter out the cell-cell communication if there are only few number of cells in certain cell groups
cellchat.int.new.control <- filterCommunication(cellchat.int.new.control, min.cells = 10)

df.net.int.ctrl <- subsetCommunication(cellchat.int.new.control) 

 

cellchat.int.new.control <- computeCommunProbPathway(cellchat.int.new.control)
```



```{r fig.height=4, fig.width=6}
#Visualize the results
cellchat.int.new.control <- aggregateNet(cellchat.int.new.control)

groupSize <- as.numeric(table(cellchat.int.new.control@idents))
par(mfrow = c(1,2), xpd=TRUE)

netVisual_circle(cellchat.int.new.control@net$count, vertex.weight = groupSize, weight.scale = T, vertex.label.color = adjustcolor("black"),label.edge= F,color.use=c(  "#984EA3","#FF7F00" ,"#F781BF","#A65628","#377EB8","#1B9E77","#E41A1C","#8DD3C7" ,"#Acba9d", "#666666" ,"#d78a7d" ),)

netVisual_circle(cellchat.int.new.control@net$weight, vertex.weight = groupSize, weight.scale = T, vertex.label.color = adjustcolor("black"),label.edge= F,  
                 color.use=c(  "#984EA3","#FF7F00" ,"#F781BF","#A65628","#377EB8","#1B9E77","#E41A1C","#8DD3C7" ,"#Acba9d", "#666666" ,"#d78a7d" ))


```


```{r}
#plotting with designated sender(s) and receiver(s)

netVisual_chord_gene(cellchat.int.new.control, targets.use = c(3,5),  sources.use = c(1),lab.cex = 1,legend.pos.y = 20)
```



