```{r fig.height=4.5, fig.width=6}
# Load packages providing functions
library(Seurat)
library(dplyr)
library(patchwork)
library(Matrix)
library(cowplot)
library(ggplot2)
library(RColorBrewer)
library(ggrepel)
library(future)
library(tidyverse)
library(reshape2)

```


```{r}
######## Process Treated and Control datasets

data.Control <- Read10X(data.dir = "/Users/bg/Desktop/Control")

data.Treated <- Read10X(data.dir = "/Users/bg/Desktop/Treatment")


data.Control <- CreateSeuratObject(data.Control, assay = "RNA",
                                   min.cells = 3, # Include genes with detected expression in at least this many cells (3 cells)
                                   min.features = 200, # Include cells where at least this many genes are detected (200 genes)
                                   project = 'Control')

data.Control <- RenameCells(data.Control, add.cell.id = "Control")
data.Control@meta.data$sample <- "Control"
data.Control[["percent.mt"]] <- PercentageFeatureSet(data.Control, pattern = "^mt-")
data.Control[["percent.ribo"]] <- PercentageFeatureSet(data.Control, pattern = "^rp")
VlnPlot(data.Control, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0.01)
data.Control_clean <- subset(data.Control, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 20)


num_cells_control_clean<- ncol(data.Control_clean)

data.Treated <- CreateSeuratObject(data.Treated, assay = "RNA",
                                   min.cells = 3, # Include genes with detected expression in at least this many cells (3 cells)
                                   min.features = 200, # Include cells where at least this many genes are detected (200 genes)
                                   project = 'Treated')


data.Treated <- RenameCells(data.Treated, add.cell.id = "Treated")
data.Treated@meta.data$sample <- "Treated"
data.Treated[["percent.mt"]] <- PercentageFeatureSet(data.Treated, pattern = "^mt-")
data.Treated[["percent.ribo"]] <- PercentageFeatureSet(data.Treated, pattern = "^rp")
VlnPlot(data.Treated, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0.01)
data.Treated_clean <- subset(data.Treated, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 20)
```

```{r}
data.Depleted_clean_subsampled <- data.Treated_clean[, sample(colnames(data.Treated_clean), size = 3328, replace=F)]

num_cells_treated_clean_subsample <- ncol(data.Depleted_clean_subsampled)


data.integrated <- merge(data.Control_clean,data.Depleted_clean_subsampled)

# In Seurat V5, RNA assays from different samples are stored in separate layers. To analyze the cells as a single sample, integrate these layers.
data.integrated[["RNA"]] <- JoinLayers(data.integrated[["RNA"]])
```


```{r}
data.integrated <- NormalizeData(data.integrated, verbose = T)
data.integrated <- FindVariableFeatures(data.integrated, selection.method = "vst", nfeatures = 2500, verbose = T)
data.integrated <- ScaleData(data.integrated, features=rownames(data.integrated),verbose = T)
data.integrated <- RunPCA(data.integrated, pc.genes = data.integrated@var.genes, npcs = 30, verbose = T)
ElbowPlot(data.integrated, ndims = 30)
```

```{r}
data.integrated <- FindNeighbors(data.integrated, dims = 1:15)
data.integrated <- FindClusters(data.integrated, resolution = 1.0)
data.integrated <- RunUMAP(data.integrated, dims = 1:15)
```

```{r fig.height=6.2, fig.width=5.8}
## Plot and take a look at the data
color.vector <- c( brewer.pal(12, "Set3"),brewer.pal(8, "Set1"), brewer.pal(8, "Dark2"), brewer.pal(8, "Accent"),brewer.pal(8, "Pastel1"))
DimPlot(data.integrated, reduction = "umap", pt.size = 0.1, label = T, cols = color.vector,repel=T,group.by="seurat_clusters",shuffle=T)

DimPlot(data.integrated, reduction = "umap", pt.size = 0.1, label = F, group.by="sample", cols = c("blue","red"),shuffle=T)
```

```{r fig.height=6, fig.width=11.5}
#Plot the expression patterns of some key markers
DotPlot(data.integrated,group.by="seurat_clusters",features=c("Cd68","Adgre1","Cd209a","H2-Aa","H2-Ab1","Nkg7","Cd3d","Pdgfra","Dcn","Pecam1","Cdh5","Tnni2","Tnnc2","Tnnt3","Mreg","Pax7","Myod1","Myog","S100a8","S100a9","Rgs5","Myh11"),  cols = c("lightgrey", "#35553B"))+ RotatedAxis() + ylab(NULL)+xlab('Gene') +  theme(

                    axis.title.x = element_text(size = 16),
                    axis.text.y = element_text(size = 16),
                    axis.text.x = element_text(size = 16))
```

```{r}
table(data.integrated@meta.data$RNA_snn_res.1, data.integrated@meta.data$sample)
```


```{r}
#Setting identity to each cluster

current.cluster.ids <- c(0, 1, 2, 3, 4, 5, 6, 7,8,9,10,11,12,13,14,15,16,17,18,19)
new.cluster.ids <- c("Monocytes/Macrophages",
"Monocytes/Macrophages",

"Dendritic Cells",

"Monocytes/Macrophages",
"Monocytes/Macrophages",
"Monocytes/Macrophages",
"Monocytes/Macrophages",
"Monocytes/Macrophages",
"Monocytes/Macrophages",

"Satelite Cells",
"Monocytes/Macrophages",

"FAPs",
"NK Cells",
"Monocytes/Macrophages",
"T Cells",
"Endothelial Cells",
"Type II Myonuclei",
"Mreg+ Anitgen Presenting Cells",
"Monocytes/Macrophages",
"Pericytes/Smooth Muscle Cells"
)

data.integrated@meta.data$cellid <- data.integrated@meta.data$seurat_clusters
data.integrated@meta.data[["cellid"]] <- plyr::mapvalues(x = data.integrated@meta.data[["cellid"]], from = current.cluster.ids, to = new.cluster.ids)
```

```{r fig.height=4, fig.width=8}

color.vector <- c( "#984EA3","#FF7F00" ,"#F781BF","#A65628","#666666","#1B9E77","#E41A1C","#8DD3C7" ,"#Acba9d", "#377EB8" ,"#d78a7d")


DimPlot(data.integrated, reduction = "umap", pt.size = 0.15, label = F, cols = color.vector,group.by="cellid",split.by="sample",repel=T)




count_table <- table(data.integrated@meta.data$cellid, data.integrated@meta.data$sample)

# Convert to percentages by column
percent_table <- prop.table(count_table, margin = 2) * 100

# View result
round(percent_table, 2)
```

```{r fig.height=4, fig.width=11.5}
#Plot the expression patterns of some key markers
DotPlot(data.integrated,group.by="cellid",features=c("Cd68","Adgre1","Cd209a","H2-Aa","H2-Ab1","Nkg7","Cd3d","Pdgfra","Dcn","Pecam1","Cdh5","Tnni2","Tnnc2","Tnnt3","Mreg","Pax7","Myod1","Myog","S100a8","S100a9","Rgs5","Myh11"),  cols = c("lightgrey", "#35553B"))+ RotatedAxis() + ylab(NULL)+xlab('Gene') +  theme(

                    axis.title.x = element_text(size = 16),
                    axis.text.y = element_text(size = 16),
                    axis.text.x = element_text(size = 16))
```


```{r fig.height=10, fig.width=12.5}
DefaultAssay(data.integrated) <- "RNA"
Idents(data.integrated) <- "cellid"
inj_markers_all_RNA <- FindAllMarkers(object = data.integrated, only.pos = T, min.pct = 0.25, logfc.threshold = 0.25) 

pval <- inj_markers_all_RNA[,c(1)]
adj_p <- p.adjust(pval, method = "BH", n = length(pval))

inj_markers_all_RNA$adj_pval <- adj_p

inj_markers_all_RNA_subset <- inj_markers_all_RNA %>% filter(adj_pval <= 0.05)


top10 <- inj_markers_all_RNA_subset %>% group_by(cluster) %>% top_n(n = 5, wt = avg_log2FC)




DoHeatmap(data.integrated, features = top10$gene,group.color=c("#984EA3","#FF7F00" ,"#F781BF","#A65628","#377EB8","#1B9E77","#E41A1C","#8DD3C7" ,"#Acba9d", "#666666" ,"#d78a7d" )) + scale_fill_gradientn(colors = c("blue", "white", "red"))
```


```{r fig.height=7, fig.width=7}

#Volcano Plot

library(EnhancedVolcano)
library(nichenetr)
library(tibble)

Idents(data.integrated) <- "cellid"
seurat_obj_receiver <- subset(data.integrated)
Idents(seurat_obj_receiver) <- "sample"
DE_table_receiver =  FindMarkers(object = seurat_obj_receiver, ident.1 = "Treated", ident.2 = "Control",logfc.threshold = 0, min.pct = 0.1, verbose = T) %>% rownames_to_column("gene")

pval <- DE_table_receiver[,c(2)]
adj_p <- p.adjust(pval, method = "BH", n = length(pval))

DE_table_receiver$adj_pval <- adj_p


EnhancedVolcano(DE_table_receiver,
                
                  title=("Unknown"),
    #lab = DE_table_receiver$gene,
     lab = rep(NA, nrow(DE_table_receiver)), 
    x = 'avg_log2FC',
    y = 'adj_pval',
      pCutoff = 5e-02,

  FCcutoff = 0.5,
  xlim=c(-10,10),
  #ylim=c(-0,20),
  xlab = bquote(~Log[2]~ 'fold change'),
ylab = bquote('-'~Log[10]~ 'adj p-value'),  
  legendLabels=c('Not sig.','Not sig.',bquote('DEGs'~' '~Log[2]~'FC <= 0.5'),
      'DEGs'~' '~Log[2]~'FC > 0.5'),
col=c('grey30', 'grey30', 'royalblue', 'red3'),
legendPosition = 'none',
    #legendPosition = 'right',
 pointSize = 3.0,
    labSize = 8,
axisLabSize = 30
  )+ theme(

  axis.text.x = element_text(color = "black"),
  axis.text.y = element_text(color = "black")
)

```



```{r}
library(CellChat)
library(patchwork)
options(stringsAsFactors = FALSE)
```

```{r} 
precellchat.int.new.control <- subset(x = data.integrated, subset = sample == "Control")
cellchat.int.new.control <- createCellChat(object = precellchat.int.new.control, group.by = "cellid", assay = "RNA")
```


```{r}
CellChatDB <- CellChatDB.mouse 
showDatabaseCategory(CellChatDB)
# Show the structure of the database
dplyr::glimpse(CellChatDB$interaction)
CellChatDB.use <- CellChatDB
# set the used database in the object
cellchat.int.new.control@DB <- CellChatDB.use
```

```{r}
# subset the expression data of signaling genes for saving computation cost
cellchat.int.new.control <- subsetData(cellchat.int.new.control) # This step is necessary even if using the whole database
future::plan("multisession", workers = 8) # do parallel
cellchat.int.new.control <- identifyOverExpressedGenes(cellchat.int.new.control)
cellchat.int.new.control <- identifyOverExpressedInteractions(cellchat.int.new.control)
```

```{r}
cellchat.int.new.control <- computeCommunProb(cellchat.int.new.control)
# Filter out the cell-cell communication if there are only few number of cells in certain cell groups
cellchat.int.new.control <- filterCommunication(cellchat.int.new.control, min.cells = 10)

df.net.int.ctrl <- subsetCommunication(cellchat.int.new.control) 

 

cellchat.int.new.control <- computeCommunProbPathway(cellchat.int.new.control)
```


```{r fig.height=8, fig.width=6}
#Visualize the results
cellchat.int.new.control <- aggregateNet(cellchat.int.new.control)

groupSize <- as.numeric(table(cellchat.int.new.control@idents))
par(mfrow = c(1,2), xpd=TRUE)

netVisual_circle(cellchat.int.new.control@net$count, vertex.weight = groupSize, weight.scale = T, vertex.label.color = adjustcolor("black", alpha.f = 1),label.edge= F, vertex.label.cex = 0.45,  title.name = "Number of interactions",)

netVisual_circle(cellchat.int.new.control@net$weight, vertex.weight = groupSize, weight.scale = T, vertex.label.color = adjustcolor("black", alpha.f = 1),label.edge= F, vertex.label.cex = 0.45, title.name = "Interaction weights/strength")
```


```{r fig.height=4, fig.width=10}
#Visualize the results
cellchat.int.new.control <- aggregateNet(cellchat.int.new.control)

groupSize <- as.numeric(table(cellchat.int.new.control@idents))
par(mfrow = c(1,2), xpd=TRUE)

netVisual_circle(cellchat.int.new.control@net$count, vertex.weight = groupSize, weight.scale = T, vertex.label.color = adjustcolor("black", alpha.f = 0),label.edge= F,color.use=c(  "#984EA3","#FF7F00" ,"#F781BF","#A65628","#377EB8","#1B9E77","#E41A1C","#8DD3C7" ,"#Acba9d", "#666666" ,"#d78a7d" ),)

netVisual_circle(cellchat.int.new.control@net$weight, vertex.weight = groupSize, weight.scale = T, vertex.label.color = adjustcolor("black", alpha.f = 0),label.edge= F,
                 color.use=c(  "#984EA3","#FF7F00" ,"#F781BF","#A65628","#377EB8","#1B9E77","#E41A1C","#8DD3C7" ,"#Acba9d", "#666666" ,"#d78a7d" ))
```
